[[Variable]]
  Name = "Copay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Dstatus"
  GoType = "uint8"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Deduct"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Dx1"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx2"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx3"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx4"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx5"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx6"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx7"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx8"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx9"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Enrolid"
  GoType = "uint64"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Netpay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Proc1"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc2"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc3"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc4"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc5"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc6"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Seqnum"
  GoType = "uint64"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Svcdate"
  GoType = "uint16"
  SASType = "float64"
  Must = true
