[[Variable]]
  Name = "Admtyp"
  GoType = "uint8"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Admdate"
  GoType = "uint16"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Disdate"
  GoType = "uint16"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Drg"
  GoType = "uint16"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Dstatus"
  GoType = "uint8"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx1"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx2"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx3"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx4"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx5"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx6"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx7"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx8"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx9"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx10"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx11"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx12"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx13"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx14"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx15"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Enrolid"
  GoType = "uint64"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Hospnet"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Hosppay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Proc1"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc2"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc3"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc4"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc5"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc6"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc7"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc8"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc9"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc10"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc11"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc12"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc13"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc14"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Proc15"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Physnet"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Physpay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Seqnum"
  GoType = "uint64"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Totpay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Totcoins"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Totcopay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Totded"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Totnet"
  GoType = "float32"
  SASType = "float64"
  Must = true
