[[Variable]]
  Name = "Seqnum"
  GoType = "uint64"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Enrolid"
  GoType = "uint64"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Dx1"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx2"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Dx3"
  GoType = "string"
  SASType = "string"
  Must = false

[[Variable]]
  Name = "Dx4"
  GoType = "string"
  SASType = "string"
  Must = false

[[Variable]]
  Name = "Proc1"
  GoType = "string"
  SASType = "string"
  Must = true

[[Variable]]
  Name = "Procgrp"
  GoType = "uint16"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Svcdate"
  GoType = "uint16"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Copay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Deduct"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Stdprov"
  GoType = "uint16"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Netpay"
  GoType = "float32"
  SASType = "float64"
  Must = true

[[Variable]]
  Name = "Svcscat"
  GoType = "uint32"
  SASType = "string"
  Must = true
