SourceDir = "/nfs/turbo/ihpi-dads/MarketScan/Data"
SASFiles = ["2009/ccaea093.sas7bdat", "2010/ccaea103.sas7bdat", "2011/ccaea113.sas7bdat",
	    "2012/ccaea122.sas7bdat", "2013/ccaea131.sas7bdat", "2014/ccaea142.sas7bdat",
	    "2015/ccaea151.sas7bdat"]
TargetDir = "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/A"
CodesDir - "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/Codes"
SASChunkSize = 1000000
NumBuckets = 100
BufMaxRecs = 500000
MaxChunk = 0
