SourceDir = "/nfs/turbo/ihpi-dads/MarketScan/Data"
SASFiles = ["2009/ccaef093.sas7bdat", "2010/ccaef103.sas7bdat", "2011/ccaef113.sas7bdat",
	    "2012/ccaef122.sas7bdat", "2013/ccaef131.sas7bdat", "2014/ccaef142.sas7bdat",
	    "2015/ccaef151.sas7bdat"]
TargetDir = "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/F"
CodesDir = "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/Codes"
SASChunkSize = 1000000
NumBuckets = 100
BufMaxRecs = 500000
MaxChunk = 0
