SourceDir = "/nfs/turbo/ihpi-dads/MarketScan/Data"
SASFiles = ["2009/ccaei093.sas7bdat", "2010/ccaei103.sas7bdat", "2011/ccaei113.sas7bdat",
	    "2012/ccaei122.sas7bdat", "2013/ccaei131.sas7bdat", "2014/ccaei142.sas7bdat",
	    "2015/ccaei151.sas7bdat"]
TargetDir = "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/I"
CodesDir = "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/Codes"
SASChunkSize = 1000000
NumBuckets = 100,
BufMaxRecs = 500000
MaxChunk = 0
