SourceDir = "/nfs/turbo/ihpi-dads/MarketScan/Data"
SASFiles = ["2009/ccaes093.sas7bdat", "2010/ccaes103.sas7bdat", "2011/ccaes113.sas7bdat",
	    "2012/ccaes122.sas7bdat", "2013/ccaes131.sas7bdat", "2014/ccaes142.sas7bdat",
	    "2015/ccaes151.sas7bdat"]
TargetDir = "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/S"
CodesDir = "/nfs/turbo/ihpi-dads/CSCAR/MarketScan/Codes"
SASChunkSize = 1000000
NumBuckets = 100,
BufMaxRecs = 500000
MaxChunk = 0
